while True:
    print('-'*40)
    print(f"{'MENU PRINCIPAL':^40}")
    print('-'*40)
    print('\033[0;33m1 - \033[m\033[0;34mVer pessoas cadastradas')
    print('\033[0;33m2 - \033[m\033[0;34mCadastrar nova pessoa')
    print('\033[0;33m3 - \033[m\033[0;34mSair do sistema')
    print('-'*40)
    resposta = int(input('\033[0;33mSua Opção: \033[m'))
    print('-'*40) 
    if resposta == 1:
        print('-'*40)
        print(f"{'PESSOAS CADASTRADAS':^40}")
        print('-'*40)
        arquivo = open("pessoasCadastradas.txt", "r")
        conteudo = arquivo.read()
        print(conteudo)
    elif resposta == 2:
        print('-'*40)
        print(f"{'NOVO CADASTRO':^40}")
        print('-'*40)
        arquivo = open("pessoasCadastradas.txt", "w")
        nome = str(input('NOME:'))
        arquivo.write(nome)
        arquivo.write(input('IDADE:'))
        print(f'Novo resgistro de {nome} adicionado.')
        arquivo.close()
    elif resposta == 3:
        print('-'*40)
        print(f"{'Saindo do sistema... Até logo!':^40}")
        print('-'*40)
        break
